### ISSUE TITLE
fix branch dev and merge to master

### ISSUE THREAD

**Issue by hellyworld** [GhitaAlexandruIon/social#3]
- [ ] create a new branch from master
- [ ] check dev for important code
- [ ] merge new master to new branch
- [ ] check integrity (the program is working)
- [ ] merge new branch to master - after the code was checked and approved
- [ ] delete dev branch

**Comment by hellyworld** [comment]
`print("hello")`

**Comment by hellyworld** [comment]
- [x] task one

- [x] task two

**Comment by GhitaAlexandruIon** [comment]
delete dev
